n_epoch: 100
batch_size: 64
save_dir: &save_dir log/celeba_unet_resnet2_l2
device: "cuda"
data_parallel: true

dataset:
  name: CelebADataset
  params: {}

model:
  ae:
    name: UNet
    params:
       n_channels: 3
       n_classes: 3
    opt_params:
      lr: 0.0001
  potential:
    name: ResNet_D
    params: {}
    opt_params:
      lr: 0.0001

cost:
  name: L2Cost

train_params: {}

wandb_init_params: &wandb_init_params
  project: &wandb_project not_ae
  entity: &wandb_account sverdoot
  name: 'celeba_l2'
  # config: *params

callbacks:
  - name: TrainLogCallback
    params:
      invoke_every: 1
  # - FID:
  #     name: FIDCallback
  #     params:
  #       data_stat_path: stats/celeba_fid_stats_test.np
  #       invoke_every: 1
  # - LPIPS:
  #     name: LPIPSDCallback
  #     params:
  #       invoke_every: 1
  # - LogMetrics:
  #     name: LogCallback
  #     params:
  #       invoke_every: 1
  #       keys:
  #         - fid
  #         - lpips
  - name: WandbCallback
    params:
      keys:
        - loss_ae
        - loss_potential
        - imgs
      invoke_every: 1
      init_params: *wandb_init_params

