n_epoch: 10
batch_size: 128
save_dir: &save_dir log/celeba_unet_resnet2_l2
device: "cuda"
data_parallel: true

dataset:
  name: CelebADataset
  params: {}

model:
  ae:
    name: UNet
    params:
      n_channels: 3
      n_classes: 3
    opt_params:
      lr: 0.0003
      weight_decay: 0.0001
  potential:
    name: ResNet_D
    params:
      bn: false
    opt_params:
      lr: 0.0003
      weight_decay: 0.0001

cost:
  name: L2Cost

train_params:
  n_ae: 10
  n_potential: 1
  eval_every: 1

wandb_init_params: &wandb_init_params
  project: &wandb_project not_ae
  entity: &wandb_account sverdoot
  name: 'celeba_l2'
  # config: 
  #   <<

callbacks:
  - name: TrainLogCallback
    params:
      invoke_every: 100
      step_key: batch_id
  - name: FIDCallback
    params:
      data_stat_path: stats/celeba_fid_stats_test.npz
      invoke_every: 1
      step_key: epoch_id
  - name: LPIPSCallback
    params:
      invoke_every: 1
      step_key: epoch_id
      test_dataset: null
  - name: LogCallback
    params:
      invoke_every: 1
      keys:
        - fid
        - lpips
      step_key: epoch_id
      save_dir: *save_dir
  - name: WandbCallback
    params:
      keys:
        - loss_ae
        - loss_potential
        - imgs
        - origs
      invoke_every: 10
      step_key: batch_id
      init_params: *wandb_init_params
  - name: CheckpointCallback
    params:
      invoke_every: 10
      step_key: epoch_id
      save_dir: *save_dir
      ae: null
      potential: null
