n_epoch: 5
batch_size: 128
save_dir: &save_dir log/celeba_unet_dumb_l1
device: "cuda"
data_parallel: true

dataset:
  name: CelebADataset
  params: {}

model:
  ae:
    name: UNet
    params:
      n_channels: &n_channels 3
      n_classes: *n_channels
    opt_params:
      lr: 0.0001
      weight_decay: 0.0000000001
  potential:
    name: Dumb_D
    params: {}
    opt_params:
      lr: 0.0001
      weight_decay: 0.0000000001

cost:
  name: L1Cost

train_params:
  n_ae: 10
  eval_every: 1

wandb_init_params: &wandb_init_params
  project: &wandb_project not_ae
  entity: &wandb_account sverdoot
  name: 'celeba_l1_dumb'
  # config: *params

callbacks:
  - name: TrainLogCallback
    params:
      invoke_every: 100
      step_key: batch_id
  - name: FIDCallback
    params:
      data_stat_path: stats/celeba_fid_stats_val.npz
      invoke_every: 1
      step_key: epoch_id
  - name: LPIPSCallback
    params:
      invoke_every: 1
      step_key: epoch_id
      test_dataset: null
  - name: LogCallback
    params:
      invoke_every: 1
      keys:
        - fid
        - lpips
      step_key: epoch_id
      save_dir: *save_dir
  - name: WandbCallback
    params:
      keys:
        - loss_ae
        - loss_potential
        - imgs
        - origs
      invoke_every: 10
      step_key: batch_id
      init_params: *wandb_init_params
  - name: WandbCallback
    params:
      keys:
        - fid
        - lpips
      invoke_every: 1
      step_key: epoch_id
      init_params: *wandb_init_params
  - name: CheckpointCallback
    params:
      invoke_every: 1
      step_key: epoch_id
      save_dir: *save_dir
      ae: null
      potential: null

